/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { VaultGovernor__factory } from "./VaultGovernor__factory";
export { VaultTimelockController__factory } from "./VaultTimelockController__factory";
