/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface VaultMultiSigInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "EMERGENCY_ROLE"
      | "GUARDIAN_ROLE"
      | "actionWindow"
      | "approveEmergencyAction"
      | "emergencyActions"
      | "executeEmergencyAction"
      | "getApprovalCount"
      | "getRoleAdmin"
      | "grantRole"
      | "hasApproved"
      | "hasRole"
      | "proposeEmergencyAction"
      | "renounceRole"
      | "requiredGuardians"
      | "revokeApproval"
      | "revokeRole"
      | "setActionWindow"
      | "setRequiredGuardians"
      | "supportsInterface"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EmergencyActionApproved"
      | "EmergencyActionExecuted"
      | "EmergencyActionProposed"
      | "EmergencyActionRevoked"
      | "RequiredGuardiansUpdated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EMERGENCY_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GUARDIAN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "actionWindow",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveEmergencyAction",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyActions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeEmergencyAction",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getApprovalCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasApproved",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeEmergencyAction",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requiredGuardians",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeApproval",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setActionWindow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRequiredGuardians",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EMERGENCY_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GUARDIAN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "actionWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveEmergencyAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyActions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeEmergencyAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApprovalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposeEmergencyAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requiredGuardians",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setActionWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRequiredGuardians",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
}

export namespace EmergencyActionApprovedEvent {
  export type InputTuple = [actionId: BytesLike, guardian: AddressLike];
  export type OutputTuple = [actionId: string, guardian: string];
  export interface OutputObject {
    actionId: string;
    guardian: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyActionExecutedEvent {
  export type InputTuple = [actionId: BytesLike];
  export type OutputTuple = [actionId: string];
  export interface OutputObject {
    actionId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyActionProposedEvent {
  export type InputTuple = [
    actionId: BytesLike,
    proposer: AddressLike,
    target: AddressLike
  ];
  export type OutputTuple = [
    actionId: string,
    proposer: string,
    target: string
  ];
  export interface OutputObject {
    actionId: string;
    proposer: string;
    target: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyActionRevokedEvent {
  export type InputTuple = [actionId: BytesLike, guardian: AddressLike];
  export type OutputTuple = [actionId: string, guardian: string];
  export interface OutputObject {
    actionId: string;
    guardian: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequiredGuardiansUpdatedEvent {
  export type InputTuple = [oldValue: BigNumberish, newValue: BigNumberish];
  export type OutputTuple = [oldValue: bigint, newValue: bigint];
  export interface OutputObject {
    oldValue: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VaultMultiSig extends BaseContract {
  connect(runner?: ContractRunner | null): VaultMultiSig;
  waitForDeployment(): Promise<this>;

  interface: VaultMultiSigInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  EMERGENCY_ROLE: TypedContractMethod<[], [string], "view">;

  GUARDIAN_ROLE: TypedContractMethod<[], [string], "view">;

  actionWindow: TypedContractMethod<[], [bigint], "view">;

  approveEmergencyAction: TypedContractMethod<
    [actionId: BytesLike],
    [void],
    "nonpayable"
  >;

  emergencyActions: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, boolean] & {
        target: string;
        data: string;
        timestamp: bigint;
        approvalCount: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;

  executeEmergencyAction: TypedContractMethod<
    [actionId: BytesLike],
    [void],
    "nonpayable"
  >;

  getApprovalCount: TypedContractMethod<
    [actionId: BytesLike],
    [bigint],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasApproved: TypedContractMethod<
    [actionId: BytesLike, guardian: AddressLike],
    [boolean],
    "view"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  proposeEmergencyAction: TypedContractMethod<
    [target: AddressLike, data: BytesLike],
    [string],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  requiredGuardians: TypedContractMethod<[], [bigint], "view">;

  revokeApproval: TypedContractMethod<
    [actionId: BytesLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setActionWindow: TypedContractMethod<
    [newWindow: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRequiredGuardians: TypedContractMethod<
    [newRequired: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "EMERGENCY_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GUARDIAN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "actionWindow"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "approveEmergencyAction"
  ): TypedContractMethod<[actionId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyActions"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, boolean] & {
        target: string;
        data: string;
        timestamp: bigint;
        approvalCount: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "executeEmergencyAction"
  ): TypedContractMethod<[actionId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getApprovalCount"
  ): TypedContractMethod<[actionId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasApproved"
  ): TypedContractMethod<
    [actionId: BytesLike, guardian: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "proposeEmergencyAction"
  ): TypedContractMethod<
    [target: AddressLike, data: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requiredGuardians"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "revokeApproval"
  ): TypedContractMethod<[actionId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setActionWindow"
  ): TypedContractMethod<[newWindow: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRequiredGuardians"
  ): TypedContractMethod<[newRequired: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;

  getEvent(
    key: "EmergencyActionApproved"
  ): TypedContractEvent<
    EmergencyActionApprovedEvent.InputTuple,
    EmergencyActionApprovedEvent.OutputTuple,
    EmergencyActionApprovedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyActionExecuted"
  ): TypedContractEvent<
    EmergencyActionExecutedEvent.InputTuple,
    EmergencyActionExecutedEvent.OutputTuple,
    EmergencyActionExecutedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyActionProposed"
  ): TypedContractEvent<
    EmergencyActionProposedEvent.InputTuple,
    EmergencyActionProposedEvent.OutputTuple,
    EmergencyActionProposedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyActionRevoked"
  ): TypedContractEvent<
    EmergencyActionRevokedEvent.InputTuple,
    EmergencyActionRevokedEvent.OutputTuple,
    EmergencyActionRevokedEvent.OutputObject
  >;
  getEvent(
    key: "RequiredGuardiansUpdated"
  ): TypedContractEvent<
    RequiredGuardiansUpdatedEvent.InputTuple,
    RequiredGuardiansUpdatedEvent.OutputTuple,
    RequiredGuardiansUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "EmergencyActionApproved(bytes32,address)": TypedContractEvent<
      EmergencyActionApprovedEvent.InputTuple,
      EmergencyActionApprovedEvent.OutputTuple,
      EmergencyActionApprovedEvent.OutputObject
    >;
    EmergencyActionApproved: TypedContractEvent<
      EmergencyActionApprovedEvent.InputTuple,
      EmergencyActionApprovedEvent.OutputTuple,
      EmergencyActionApprovedEvent.OutputObject
    >;

    "EmergencyActionExecuted(bytes32)": TypedContractEvent<
      EmergencyActionExecutedEvent.InputTuple,
      EmergencyActionExecutedEvent.OutputTuple,
      EmergencyActionExecutedEvent.OutputObject
    >;
    EmergencyActionExecuted: TypedContractEvent<
      EmergencyActionExecutedEvent.InputTuple,
      EmergencyActionExecutedEvent.OutputTuple,
      EmergencyActionExecutedEvent.OutputObject
    >;

    "EmergencyActionProposed(bytes32,address,address)": TypedContractEvent<
      EmergencyActionProposedEvent.InputTuple,
      EmergencyActionProposedEvent.OutputTuple,
      EmergencyActionProposedEvent.OutputObject
    >;
    EmergencyActionProposed: TypedContractEvent<
      EmergencyActionProposedEvent.InputTuple,
      EmergencyActionProposedEvent.OutputTuple,
      EmergencyActionProposedEvent.OutputObject
    >;

    "EmergencyActionRevoked(bytes32,address)": TypedContractEvent<
      EmergencyActionRevokedEvent.InputTuple,
      EmergencyActionRevokedEvent.OutputTuple,
      EmergencyActionRevokedEvent.OutputObject
    >;
    EmergencyActionRevoked: TypedContractEvent<
      EmergencyActionRevokedEvent.InputTuple,
      EmergencyActionRevokedEvent.OutputTuple,
      EmergencyActionRevokedEvent.OutputObject
    >;

    "RequiredGuardiansUpdated(uint256,uint256)": TypedContractEvent<
      RequiredGuardiansUpdatedEvent.InputTuple,
      RequiredGuardiansUpdatedEvent.OutputTuple,
      RequiredGuardiansUpdatedEvent.OutputObject
    >;
    RequiredGuardiansUpdated: TypedContractEvent<
      RequiredGuardiansUpdatedEvent.InputTuple,
      RequiredGuardiansUpdatedEvent.OutputTuple,
      RequiredGuardiansUpdatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
