/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as gelatoCompounderSol from "./GelatoCompounder.sol";
export { ChainlinkCompounder__factory } from "./ChainlinkCompounder__factory";
