/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace TreasuryYieldManager {
  export type StrategyAllocationStruct = {
    savingsVault: BigNumberish;
    curvePool: BigNumberish;
    aerodromePool: BigNumberish;
    idle: BigNumberish;
  };

  export type StrategyAllocationStructOutput = [
    savingsVault: bigint,
    curvePool: bigint,
    aerodromePool: bigint,
    idle: bigint
  ] & {
    savingsVault: bigint;
    curvePool: bigint;
    aerodromePool: bigint;
    idle: bigint;
  };
}

export interface TreasuryYieldManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptOwnership"
      | "aerodromePoolAddress"
      | "allocation"
      | "curvePoolAddress"
      | "deployTreasury"
      | "getTotalValue"
      | "harvestAll"
      | "musdSavingsVault"
      | "musdToken"
      | "owner"
      | "pendingOwner"
      | "renounceOwnership"
      | "savingsVaultShares"
      | "setAerodromePool"
      | "setAllocation"
      | "setCurvePool"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DepositedToStrategy"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "StrategyRebalanced"
      | "YieldHarvested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "aerodromePoolAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allocation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "curvePoolAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployTreasury",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalValue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "harvestAll",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "musdSavingsVault",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "musdToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "savingsVaultShares",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAerodromePool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAllocation",
    values: [TreasuryYieldManager.StrategyAllocationStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setCurvePool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "aerodromePoolAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allocation", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "curvePoolAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "harvestAll", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "musdSavingsVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "musdToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "savingsVaultShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAerodromePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAllocation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCurvePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace DepositedToStrategyEvent {
  export type InputTuple = [strategy: string, amount: BigNumberish];
  export type OutputTuple = [strategy: string, amount: bigint];
  export interface OutputObject {
    strategy: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StrategyRebalancedEvent {
  export type InputTuple = [
    oldAlloc: TreasuryYieldManager.StrategyAllocationStruct,
    newAlloc: TreasuryYieldManager.StrategyAllocationStruct
  ];
  export type OutputTuple = [
    oldAlloc: TreasuryYieldManager.StrategyAllocationStructOutput,
    newAlloc: TreasuryYieldManager.StrategyAllocationStructOutput
  ];
  export interface OutputObject {
    oldAlloc: TreasuryYieldManager.StrategyAllocationStructOutput;
    newAlloc: TreasuryYieldManager.StrategyAllocationStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldHarvestedEvent {
  export type InputTuple = [totalAssets: BigNumberish, yield_: BigNumberish];
  export type OutputTuple = [totalAssets: bigint, yield_: bigint];
  export interface OutputObject {
    totalAssets: bigint;
    yield: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TreasuryYieldManager extends BaseContract {
  connect(runner?: ContractRunner | null): TreasuryYieldManager;
  waitForDeployment(): Promise<this>;

  interface: TreasuryYieldManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  aerodromePoolAddress: TypedContractMethod<[], [string], "view">;

  allocation: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        savingsVault: bigint;
        curvePool: bigint;
        aerodromePool: bigint;
        idle: bigint;
      }
    ],
    "view"
  >;

  curvePoolAddress: TypedContractMethod<[], [string], "view">;

  deployTreasury: TypedContractMethod<
    [totalAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getTotalValue: TypedContractMethod<[], [bigint], "view">;

  harvestAll: TypedContractMethod<[], [bigint], "nonpayable">;

  musdSavingsVault: TypedContractMethod<[], [string], "view">;

  musdToken: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  savingsVaultShares: TypedContractMethod<[], [bigint], "view">;

  setAerodromePool: TypedContractMethod<
    [_aerodromePool: AddressLike],
    [void],
    "nonpayable"
  >;

  setAllocation: TypedContractMethod<
    [newAlloc: TreasuryYieldManager.StrategyAllocationStruct],
    [void],
    "nonpayable"
  >;

  setCurvePool: TypedContractMethod<
    [_curvePool: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "aerodromePoolAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "allocation"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        savingsVault: bigint;
        curvePool: bigint;
        aerodromePool: bigint;
        idle: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "curvePoolAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deployTreasury"
  ): TypedContractMethod<[totalAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getTotalValue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "harvestAll"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "musdSavingsVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "musdToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "savingsVaultShares"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setAerodromePool"
  ): TypedContractMethod<[_aerodromePool: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAllocation"
  ): TypedContractMethod<
    [newAlloc: TreasuryYieldManager.StrategyAllocationStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCurvePool"
  ): TypedContractMethod<[_curvePool: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DepositedToStrategy"
  ): TypedContractEvent<
    DepositedToStrategyEvent.InputTuple,
    DepositedToStrategyEvent.OutputTuple,
    DepositedToStrategyEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "StrategyRebalanced"
  ): TypedContractEvent<
    StrategyRebalancedEvent.InputTuple,
    StrategyRebalancedEvent.OutputTuple,
    StrategyRebalancedEvent.OutputObject
  >;
  getEvent(
    key: "YieldHarvested"
  ): TypedContractEvent<
    YieldHarvestedEvent.InputTuple,
    YieldHarvestedEvent.OutputTuple,
    YieldHarvestedEvent.OutputObject
  >;

  filters: {
    "DepositedToStrategy(string,uint256)": TypedContractEvent<
      DepositedToStrategyEvent.InputTuple,
      DepositedToStrategyEvent.OutputTuple,
      DepositedToStrategyEvent.OutputObject
    >;
    DepositedToStrategy: TypedContractEvent<
      DepositedToStrategyEvent.InputTuple,
      DepositedToStrategyEvent.OutputTuple,
      DepositedToStrategyEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "StrategyRebalanced(tuple,tuple)": TypedContractEvent<
      StrategyRebalancedEvent.InputTuple,
      StrategyRebalancedEvent.OutputTuple,
      StrategyRebalancedEvent.OutputObject
    >;
    StrategyRebalanced: TypedContractEvent<
      StrategyRebalancedEvent.InputTuple,
      StrategyRebalancedEvent.OutputTuple,
      StrategyRebalancedEvent.OutputObject
    >;

    "YieldHarvested(uint256,uint256)": TypedContractEvent<
      YieldHarvestedEvent.InputTuple,
      YieldHarvestedEvent.OutputTuple,
      YieldHarvestedEvent.OutputObject
    >;
    YieldHarvested: TypedContractEvent<
      YieldHarvestedEvent.InputTuple,
      YieldHarvestedEvent.OutputTuple,
      YieldHarvestedEvent.OutputObject
    >;
  };
}
