/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IGaugeControllerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimRewards"
      | "claimRewardsForGauge"
      | "gauges"
      | "getActiveGauges"
      | "pendingRewards"
      | "vote"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "claimRewards",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRewardsForGauge",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "gauges", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "getActiveGauges",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingRewards",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRewardsForGauge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gauges", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getActiveGauges",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
}

export interface IGaugeController extends BaseContract {
  connect(runner?: ContractRunner | null): IGaugeController;
  waitForDeployment(): Promise<this>;

  interface: IGaugeControllerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimRewards: TypedContractMethod<
    [tokenId: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  claimRewardsForGauge: TypedContractMethod<
    [tokenId: BigNumberish, gauge: AddressLike],
    [bigint],
    "nonpayable"
  >;

  gauges: TypedContractMethod<
    [gauge: AddressLike],
    [
      [bigint, bigint, bigint] & {
        totalWeight: bigint;
        rewardRate: bigint;
        periodFinish: bigint;
      }
    ],
    "view"
  >;

  getActiveGauges: TypedContractMethod<[], [string[]], "view">;

  pendingRewards: TypedContractMethod<
    [tokenId: BigNumberish],
    [bigint],
    "view"
  >;

  vote: TypedContractMethod<
    [tokenId: BigNumberish, gauge: AddressLike, weight: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimRewards"
  ): TypedContractMethod<[tokenId: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "claimRewardsForGauge"
  ): TypedContractMethod<
    [tokenId: BigNumberish, gauge: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gauges"
  ): TypedContractMethod<
    [gauge: AddressLike],
    [
      [bigint, bigint, bigint] & {
        totalWeight: bigint;
        rewardRate: bigint;
        periodFinish: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getActiveGauges"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "pendingRewards"
  ): TypedContractMethod<[tokenId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [tokenId: BigNumberish, gauge: AddressLike, weight: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
