/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC4626 } from "./IERC4626";
export type { IGaugeController } from "./IGaugeController";
export type { IMUSD } from "./IMUSD";
export type { IMUSDSavingsVault } from "./IMUSDSavingsVault";
export type { ITigrisRouter } from "./ITigrisRouter";
export type { IVeMEZO } from "./IVeMEZO";
