/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VaultGovernor } from "./VaultGovernor";
export type { VaultTimelockController } from "./VaultTimelockController";
