/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface GelatoCompounderInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "automate"
      | "cancelTask"
      | "checker"
      | "createTask"
      | "executeCompound"
      | "lastExecution"
      | "minInterval"
      | "owner"
      | "setMinInterval"
      | "taskId"
      | "transferOwnership"
      | "vault"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CompoundedViaGelato"
      | "MinIntervalUpdated"
      | "OwnershipTransferred"
      | "TaskCancelled"
      | "TaskCreated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "automate", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "cancelTask",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "checker", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createTask",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeCompound",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastExecution",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minInterval",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setMinInterval",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "taskId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;

  decodeFunctionResult(functionFragment: "automate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancelTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "checker", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeCompound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastExecution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMinInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "taskId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;
}

export namespace CompoundedViaGelatoEvent {
  export type InputTuple = [
    totalRewards: BigNumberish,
    fee: BigNumberish,
    compounded: BigNumberish
  ];
  export type OutputTuple = [
    totalRewards: bigint,
    fee: bigint,
    compounded: bigint
  ];
  export interface OutputObject {
    totalRewards: bigint;
    fee: bigint;
    compounded: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinIntervalUpdatedEvent {
  export type InputTuple = [
    oldInterval: BigNumberish,
    newInterval: BigNumberish
  ];
  export type OutputTuple = [oldInterval: bigint, newInterval: bigint];
  export interface OutputObject {
    oldInterval: bigint;
    newInterval: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCancelledEvent {
  export type InputTuple = [taskId: BytesLike];
  export type OutputTuple = [taskId: string];
  export interface OutputObject {
    taskId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCreatedEvent {
  export type InputTuple = [taskId: BytesLike];
  export type OutputTuple = [taskId: string];
  export interface OutputObject {
    taskId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GelatoCompounder extends BaseContract {
  connect(runner?: ContractRunner | null): GelatoCompounder;
  waitForDeployment(): Promise<this>;

  interface: GelatoCompounderInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  automate: TypedContractMethod<[], [string], "view">;

  cancelTask: TypedContractMethod<[], [void], "nonpayable">;

  checker: TypedContractMethod<
    [],
    [[boolean, string] & { canExec: boolean; execPayload: string }],
    "view"
  >;

  createTask: TypedContractMethod<[], [string], "nonpayable">;

  executeCompound: TypedContractMethod<[], [void], "nonpayable">;

  lastExecution: TypedContractMethod<[], [bigint], "view">;

  minInterval: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  setMinInterval: TypedContractMethod<
    [_interval: BigNumberish],
    [void],
    "nonpayable"
  >;

  taskId: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  vault: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "automate"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancelTask"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "checker"
  ): TypedContractMethod<
    [],
    [[boolean, string] & { canExec: boolean; execPayload: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "createTask"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "executeCompound"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "lastExecution"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minInterval"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setMinInterval"
  ): TypedContractMethod<[_interval: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "taskId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vault"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "CompoundedViaGelato"
  ): TypedContractEvent<
    CompoundedViaGelatoEvent.InputTuple,
    CompoundedViaGelatoEvent.OutputTuple,
    CompoundedViaGelatoEvent.OutputObject
  >;
  getEvent(
    key: "MinIntervalUpdated"
  ): TypedContractEvent<
    MinIntervalUpdatedEvent.InputTuple,
    MinIntervalUpdatedEvent.OutputTuple,
    MinIntervalUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TaskCancelled"
  ): TypedContractEvent<
    TaskCancelledEvent.InputTuple,
    TaskCancelledEvent.OutputTuple,
    TaskCancelledEvent.OutputObject
  >;
  getEvent(
    key: "TaskCreated"
  ): TypedContractEvent<
    TaskCreatedEvent.InputTuple,
    TaskCreatedEvent.OutputTuple,
    TaskCreatedEvent.OutputObject
  >;

  filters: {
    "CompoundedViaGelato(uint256,uint256,uint256)": TypedContractEvent<
      CompoundedViaGelatoEvent.InputTuple,
      CompoundedViaGelatoEvent.OutputTuple,
      CompoundedViaGelatoEvent.OutputObject
    >;
    CompoundedViaGelato: TypedContractEvent<
      CompoundedViaGelatoEvent.InputTuple,
      CompoundedViaGelatoEvent.OutputTuple,
      CompoundedViaGelatoEvent.OutputObject
    >;

    "MinIntervalUpdated(uint256,uint256)": TypedContractEvent<
      MinIntervalUpdatedEvent.InputTuple,
      MinIntervalUpdatedEvent.OutputTuple,
      MinIntervalUpdatedEvent.OutputObject
    >;
    MinIntervalUpdated: TypedContractEvent<
      MinIntervalUpdatedEvent.InputTuple,
      MinIntervalUpdatedEvent.OutputTuple,
      MinIntervalUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TaskCancelled(bytes32)": TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;
    TaskCancelled: TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;

    "TaskCreated(bytes32)": TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;
    TaskCreated: TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;
  };
}
