/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GelatoCompounder__factory } from "./GelatoCompounder__factory";
export { IAutomate__factory } from "./IAutomate__factory";
